# -*- mode: ruby -*-
# vi: set ft=ruby :

map = {
    'cpu' => '1',
    'memory' => '2048',
    'promiscuous' => 'allow-all',
}

Vagrant.configure(2) do |config|
  config.vm.box = ENV['BOX_NAME']
  config.vm.base_address

  config.vm.define vm_name do |c|
    c.vm.host_name = ENV['CONTROLLER']
    c.vm.base_address = ENV['NAT_IP']

    c.vm.network 'private_network', ip: ENV['INT_IP'] # eth1
  end

  config.vm.provider 'virtualbox' do |v|
    v.customize ['modifyvm', :id, '--cpus', map['cpu']]
    v.customize ['modifyvm', :id, '--memory', map['memory']]
    v.customize ["modifyvm", :id, "--nicpromisc2", map['memory']]
  end

  config.vm.network "forwarded_port", guest: 80, host: 8080

end