---

- name: Store known hosts
  hosts: localhost
  gather_facts: false
  roles:
    - ssh_key_gen

- name: Start installation
  hosts: controller
  gather_facts: false
  become: yes
  tasks:
    - name: Disable Firewall and NetwokManager
      service:
        name: "{{ item }}"
        state: stopped
        enabled: False
      with_items:
        - firewalld
        - NetworkManager

    - name: Install requirements
      yum:
        name:
          - wget
          - curl
          - https://www.rdoproject.org/repos/rdo-release.rpm
        state: latest

    - name: Update box
      yum:
        name: "*"
        state: latest

    - name: Install Packstack packages
      yum:
        name:
          - openstack-packstack
          - openstack-utils
        state: present

    - name: Download Cirros image
      get_url:
        url: http://download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img
        dest: /root/

- name: Run packstack
  hosts: controller
  gather_facts: false
  become: yes
  roles:
    - run_packstack

- name: Configure cloud module
  hosts: controller
  gather_facts: false
  become: yes
  roles:
    - gen_cloud_file

- name: Configure Openstack
  hosts: controller
  gather_facts: false
  become: yes
  roles:
    - configure_packstack

- name: Apply settings
  hosts: controller
  gather_facts: false
  tasks:
    - name: Restart Box
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 10
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
      become: true

    - name: Waiting for server to come back
      wait_for: host="{{ ansible_host }}" port=2222 state=started delay=30 timeout=60
      delegate_to: localhost

- name: Create openstack instance
  hosts: controller
  gather_facts: false
  tasks:
    - name: Start a cirros instance
      os_server:
        cloud: mycloud
        flavor: m1.nano
        image: cirros
        key_name: mykey
        name: instance01
        security_groups: allow_ssh_http
        nics:
          - net-name: private_network

    - name: Create and assign a floating IP to the instance
      os_floating_ip:
        cloud: mycloud
        server: instance01
