- name: Remove preious host
  lineinfile:
    dest: "{{ lookup('env','HOME') + '/.ssh/known_hosts' }}"
    state: absent
    regexp: '{{ ansible_host }}'
  delegate_to: localhost

- name: Scan for its ssh public key
  shell: "ssh-keyscan -t rsa,dsa -p {{ ansible_port }} {{ ansible_host }} >> {{ lookup('env','HOME') + '/.ssh/known_hosts' }}"
  delegate_to: localhost